### ISSUE TITLE
Unable to successfully sign in unless a username is provided in `Rhapsody.member.set`

### ISSUE THREAD

**Issue by aguywithanidea** [Rhapsody/rhapsody.js#4]
The documentation in the [README](https://github.com/Rhapsody/rhapsody.js/blob/master/README.md) indicates that only two params are required to authenticate the user: `accessToken` and `refreshToken`.  However, if only providing those, the function call `Rhapsody.member.signedIn()` returns false.

```javascript
Rhapsody.member.set({
  accessToken: "VALID_USER_TOKEN",
  refreshToken: "VALID_USER_REFRESH_TOKEN"
});
console.log("signed in?", Rhapsody.member.signedIn()) 
// causes the following to print to console:  
> signed in? false
```

Conversely, providing *any* value for username will always cause `signedIn()` to return true.

```javascript
Rhapsody.member.set({
  accessToken: "VALID_USER_TOKEN",
  refreshToken: "VALID_USER_REFRESH_TOKEN",
  username: "this_value_is_completely_made_up"
});
console.log("signed in?", Rhapsody.member.signedIn()) 
// causes the following to print to console:  
> signed in? true
```

There does not appear to be any reason for `username` other than it is a required input to `Rhapsody.player.auth()`.  

What must this value be (if anything specific)?

**Comment by dudaski** [comment]
`username` should be the member's logon username (this is typically their email). This value should not be required to auth the player since the player then gets the additional user information required using the access token. I've found the offending requirement and the fix will go out in our next release. I'll update when the issue is resolved. For now though you can set it to whatever you want and it will "work" because it gets overwritten (on the player side) with the valid username.

**Comment by aguywithanidea** [comment]
Good to know that it's not currently required to be anything specific - as the oAuth endpoint does not return any identifying user information ([see this thread](https://groups.google.com/forum/#!topic/rhapsody-api/9NRuC2i2Ohg)).

Can we expect `Rhapsody.member.username` or `Rhapsody.member.guid` to be populated by the JS SDK in the future?  Or will this info be coming from the oAuth endpoint?

**Comment by dudaski** [comment]
I've removed the username requirement in v1.1.0

**Comment by aguywithanidea** [comment]
Awesome!!!
